# Dependencies
# markdown:         kramdown
# highlighter:      rouge

# Permalinks
# permalink:        pretty

# Site location
url:              https://w-donovan.github.io
baseurl:          /

# Description text
title:            'Will Donovan'
description:      ''
location:         ''


# Parameters
contact:           'Will Donovan'
contactaddr:       'donovan@mail.tsinghua.edu.cn'
calendarurl:       ''

exclude: [ "README.md" ]
